import { Language } from '../translations';

export const chartsTranslations: Record<Language, Record<string, string>> = {
  pt: {
    chart_legend: 'Legenda Cósmica de Elementos',
    fire: 'Fogo (Ação & Inspiração)',
    earth: 'Terra (Estrutura & Realismo)',
    air: 'Ar (Social & Intelecto)',
    water: 'Água (Emoção & Intuição)',
    chart_houses: 'Sistemas de Casas',
    chart_aspects: 'Aspectos Planetários Ativos',
    chart_planet_weights: 'Pesos de Atributos Personalizados',
    "Este quadro mostra a condição que cada signo, planeta e casa possui em seu mapa astral, sendo parte integrante das informações que você leu acima. Você já se perguntou por quê algumas pessoas atribuem pesos diferentes para os diversos aspects de sua personalidade ou desprendem mais ou menos energia in uma determinada área da vida? Isso acontece pois como você acompanhou até aqui, há diversas forças em jogo. Todo mapa astral é uma mistura variada de energias que criam uma configuração única, como uma espécie de DNA astral.": "Este quadro mostra a condição que cada signo, planeta e casa possui em seu mapa astral, sendo parte integrante das informações que você leu acima. Você já se perguntou por quê algumas pessoas atribuem pesos diferentes para os diversos aspects de sua personalidade ou desprendem mais ou menos energia in uma determinada área da vida? Isso acontece pois como você acompanhou até aqui, há diversas forças em jogo. Todo mapa astral é uma mistura variada de energias que criam uma configuração única, como uma espécie de DNA astral.",
    "Este quadro mostra a condição que cada signo, planeta e casa possui em seu mapa astral, sendo parte integrante das informações que você leu acima. Você já se perguntou por quê algumas pessoas atribuem pesos diferentes para os diversos aspects de sua personalidade ou desprendem mais ou menos energia em uma determinada área da vida? Isso acontece pois como você acompanhou até aqui, há diversas forças em jogo. Todo mapa astral é uma mistura variada de energias que criam uma configuração única, como uma espécie de DNA astral.": "Este quadro mostra a condição que cada signo, planeta e casa possui em seu mapa astral, sendo parte integrante das informações que você leu acima. Você já se perguntou por quê algumas pessoas atribuem pesos diferentes para os diversos aspects de sua personalidade ou desprendem mais ou menos energia em uma determinada área da vida? Isso acontece pois como você acompanhou até aqui, há diversas forças em jogo. Todo mapa astral é uma mistura variada de energias que criam uma configuração única, como uma espécie de DNA astral."
  },
  en: {
    chart_legend: 'Cosmic Elements Legend',
    fire: 'Fire (Action & Inspiration)',
    earth: 'Earth (Structure & Realism)',
    air: 'Air (Social & Intellect)',
    water: 'Water (Emotion & Intuition)',
    chart_houses: 'House Systems',
    chart_aspects: 'Active Planetary Aspects',
    chart_planet_weights: 'Custom Attribute Weights',
    "Este quadro mostra a condição que cada signo, planeta e casa possui em seu mapa astral, sendo parte integrante das informações que você leu acima. Você já se perguntou por quê algumas pessoas atribuem pesos diferentes para os diversos aspects de sua personalidade ou desprendem mais ou menos energia in uma determinada área da vida? Isso acontece pois como você acompanhou até aqui, há diversas forças em jogo. Todo mapa astral é uma mistura variada de energias que criam uma configuração única, como uma espécie de DNA astral.": "This chart shows the condition that each sign, planet, and house has in your birth chart, being an integral part of the information you read above. Have you ever wondered why some people attribute different weights to the various aspects of their personality or expend more or less energy in a certain area of life? This happens because, as you have followed so far, there are several forces at play. Every birth chart is a diverse mixture of energies that create a unique configuration, like a kind of astral DNA.",
    "Este quadro mostra a condição que cada signo, planeta e casa possui em seu mapa astral, sendo parte integrante das informações que você leu acima. Você já se perguntou por quê algumas pessoas atribuem pesos diferentes para os diversos aspects de sua personalidade ou desprendem mais ou menos energia em uma determinada área da vida? Isso acontece pois como você acompanhou até aqui, há diversas forças em jogo. Todo mapa astral é uma mistura variada de energias que criam uma configuração única, como uma espécie de DNA astral.": "This chart shows the condition that each sign, planet, and house has in your birth chart, being an integral part of the information you read above. Have you ever wondered why some people attribute different weights to the various aspects of their personality or expend more or less energy in a certain area of life? This happens because, as you have followed so far, there are several forces at play. Every birth chart is a diverse mixture of energies that create a unique configuration, like a kind of astral DNA."
  },
  es: {
    chart_legend: 'Leyenda Cósmica de Elementos',
    fire: 'Fuego (Acción e Inspiración)',
    earth: 'Tierra (Estructura y Realismo)',
    air: 'Aire (Social e Intelecto)',
    water: 'Agua (Emoción e Intuición)',
    chart_houses: 'Sistemas de Casas',
    chart_aspects: 'Aspectos Planetarios Activos',
    chart_planet_weights: 'Pesos de Atributos Personalizados',
    "Este quadro mostra a condição que cada signo, planeta e casa possui em seu mapa astral, sendo parte integrante das informações que você leu acima. Você já se perguntou por quê algumas pessoas atribuem pesos diferentes para os diversos aspects de sua personalidade ou desprendem mais ou menos energia in uma determinada área da vida? Isso acontece pois como você acompanhou até aqui, há diversas forças em jogo. Todo mapa astral é uma mistura variada de energias que criam uma configuração única, como uma espécie de DNA astral.": "Este cuadro muestra la condición que cada signo, planeta y casa posee en su mapa astral, siendo parte integrante de la información que leyó arriba. ¿Alguna vez se ha preguntado por qué algunas personas atribuyen pesos diferentes a los diversos aspectos de su personalidad o desprenden más o menos energía en un área determinada de la vida? Esto sucede porque, como ha visto hasta aquí, hay diversas fuerzas en juego. Todo mapa astral es una mezcla variada de energías que crean una configuración única, como una especie de ADN astral.",
    "Este quadro mostra a condição que cada signo, planeta e casa possui em seu mapa astral, sendo parte integrante das informações que você leu acima. Você já se perguntou por quê algumas pessoas atribuem pesos diferentes para os diversos aspects de sua personalidade ou desprendem mais ou menos energia em uma determinada área da vida? Isso acontece pois como você acompanhou até aqui, há diversas forças em jogo. Todo mapa astral é uma mistura variada de energias que criam uma configuração única, como uma espécie de DNA astral.": "Este cuadro muestra la condición que cada signo, planeta y casa posee en su mapa astral, siendo parte integrante de la información que leyó arriba. ¿Alguna vez se ha preguntado por qué algunas personas atribuyen pesos diferentes a los diversos aspectos de su personalidad o desprenden más o menos energía en un área determinada de la vida? Esto sucede porque, como ha visto hasta aquí, hay diversas fuerzas en juego. Todo mapa astral es una mezcla variada de energías que crean una configuración única, como una especie de ADN astral."
  },
  de: {
    chart_legend: 'Kosmische Elementen-Legende',
    fire: 'Feuer (Aktion & Inspiration)',
    earth: 'Erde (Struktur & Realismus)',
    air: 'Luft (Sozial & Verstand)',
    water: 'Wasser (Emotion & Intuition)',
    chart_houses: 'Häusersysteme',
    chart_aspects: 'Aktive planetarische Aspekte',
    chart_planet_weights: 'Individuelle Attributgewichtung',
    "Este quadro mostra a condição que cada signo, planeta e casa possui em seu mapa astral, sendo parte integrante das informações que você leu acima. Você já se perguntou por quê algumas pessoas atribuem pesos diferentes para os diversos aspects de sua personalidade ou desprendem mais ou menos energia in uma determinada área da vida? Isso acontece pois como você acompanhou até aqui, há diversas forças em jogo. Todo mapa astral é uma mistura variada de energias que criam uma configuração única, como uma espécie de DNA astral.": "Diese Tabelle zeigt den Zustand, den jedes Zeichen, jeder Planet und jedes Haus in Ihrem Geburtshoroskop hat, und ist ein integraler Bestandteil der Informationen, die Sie oben gelesen haben. Haben Sie sich jemals gefragt, warum manche Menschen den verschiedenen Aspekten ihrer Persönlichkeit unterschiedliche Gewichte beimessen oder mehr oder weniger Energie in einem bestimmten Lebensbereich freisetzen? Dies geschieht, weil, wie Sie bisher gesehen haben, verschiedene Kräfte im Spiel sind. Jedes Geburtshoroskop ist eine vielfältige Mischung von Energien, die eine einzigartige Konfiguration schaffen, ähnlich einer Art astraler DNA.",
    "Este quadro mostra a condição que cada signo, planeta e casa possui em seu mapa astral, sendo parte integrante das informações que você leu acima. Você já se perguntou por quê algumas pessoas atribuem pesos diferentes para os diversos aspects de sua personalidade ou desprendem mais ou menos energia em uma determinada área da vida? Isso acontece pois como você acompanhou até aqui, há diversas forças em jogo. Todo mapa astral é uma mistura variada de energias que criam uma configuração única, como uma espécie de DNA astral.": "Diese Tabelle zeigt den Zustand, den jedes Zeichen, jeder Planet und jedes Haus in Ihrem Geburtshoroskop hat, und ist ein integraler Bestandteil der Informationen, die Sie oben gelesen haben. Haben Sie sich jemals gefragt, warum manche Menschen den verschiedenen Aspekten ihrer Persönlichkeit unterschiedliche Gewichte beimessen oder mehr oder weniger Energie in einem bestimmten Lebensbereich freisetzen? Dies geschieht, weil, wie Sie bisher gesehen haben, verschiedene Kräfte im Spiel sind. Jedes Geburtshoroskop ist eine vielfältige Mischung von Energien, die eine einzigartige Konfiguration schaffen, ähnlich einer Art astraler DNA."
  },
  fr: {
    chart_legend: 'Légende Cosmique des Éléments',
    fire: 'Feu (Action & Inspiration)',
    earth: 'Terre (Structure & Réalisme)',
    air: 'Air (Social & Intellect)',
    water: 'Eau (Émotion & Intuition)',
    chart_houses: 'Systèmes de Maisons',
    chart_aspects: 'Aspects Planétaires Actifs',
    chart_planet_weights: 'Poids des Attributs Personnalisés',
    "Este quadro mostra a condição que cada signo, planeta e casa possui em seu mapa astral, sendo parte integrante das informações que você leu acima. Você já se perguntou por quê algumas pessoas atribuem pesos diferentes para os diversos aspects de sua personalidade ou desprendem mais ou menos energia in uma determinada área da vida? Isso acontece pois como você acompanhou até aqui, há diversas forças em jogo. Todo mapa astral é uma mistura variada de energias que criam uma configuração única, como uma espécie de DNA astral.": "Ce tableau montre la condition que chaque signe, planète et maison possède dans son thème astral, faisant partie intégrante des informations que vous avez lues ci-dessus. Vous êtes-vous déjà demandé pourquoi certaines personnes attribuent des poids différents aux divers aspects de leur personnalité ou dépensent plus ou moins d'énergie dans un domaine particulier de la vie ? Cela se produit car, comme vous l'avez vu jusqu'ici, plusieurs forces sont en jeu. Tout thème astral est un mélange varié d'énergies qui créent une configuration unique, comme une sorte d'ADN astral.",
    "Este quadro mostra a condição que cada signo, planeta e casa possui em seu mapa astral, sendo parte integrante das informações que você leu acima. Você já se perguntou por quê algumas pessoas atribuem pesos diferentes para os diversos aspects de sua personalidade ou desprendem mais ou menos energia em uma determinada área da vida? Isso acontece pois como você acompanhou até aqui, há diversas forças em jogo. Todo mapa astral é uma mistura variada de energias que criam uma configuração única, como uma espécie de DNA astral.": "Ce tableau montre la condition que chaque signe, planète et maison possède dans son thème astral, faisant partie intégrante des informations que vous avez lues ci-dessus. Vous êtes-vous déjà demandé pourquoi certaines personnes attribuent des poids différents aux divers aspects de leur personnalité ou dépensent plus ou moins d'énergie dans un domaine particulier de la vie ? Cela se produit car, comme vous l'avez vu jusqu'ici, plusieurs forces sont en jeu. Tout thème astral est un mélange varié d'énergies qui créent une configuration unique, comme une sorte d'ADN astral."
  }
};
