import { Language } from './types';

/**
 * Surgical completeness patch for the Tarot module.
 * It feeds the same official mergedTranslations registry used by i18next.
 * No parallel translation runtime is introduced.
 */
export const tarotCompletenessPatch: Record<Language, Record<string, string>> = {
  pt: {
    'Saiba que o Tarot é um espelho da nossa alma e reflete todo o espectro da experiência humana através de arquétipos. É uma das conexões mais antigas entre os seres humanos e as divindades, tendo o papel de nos aproximar de algo superior. Seu estudo representa uma viagem de descoberta interior, onde passamos a conhecer melhor a nós mesmos e o atual momento o qual estamos inseridos. É um oráculo que caminha lado a lado com a astrologia e a alquimia, onde em suas cartas há uma correspondência alquímica, um signo astrológico e um número para cada arquétipo. As cartas podem ser consideradas uma jornada que nos ajuda a obter uma melhor compreensão do passado, presente e futuro.': 'Saiba que o Tarot é um espelho da nossa alma e reflete todo o espectro da experiência humana através de arquétipos. É uma das conexões mais antigas entre os seres humanos e as divindades, tendo o papel de nos aproximar de algo superior. Seu estudo representa uma viagem de descoberta interior, onde passamos a conhecer melhor a nós mesmos e o atual momento o qual estamos inseridos. É um oráculo que caminha lado a lado com a astrologia e a alquimia, onde em suas cartas há uma correspondência alquímica, um signo astrológico e um número para cada arquétipo. As cartas podem ser consideradas uma jornada que nos ajuda a obter uma melhor compreensão do passado, presente e futuro.'
  },
  en: {
    'Saiba que o Tarot é um espelho da nossa alma e reflete todo o espectro da experiência humana através de arquétipos. É uma das conexões mais antigas entre os seres humanos e as divindades, tendo o papel de nos aproximar de algo superior. Seu estudo representa uma viagem de descoberta interior, onde passamos a conhecer melhor a nós mesmos e o atual momento o qual estamos inseridos. É um oráculo que caminha lado a lado com a astrologia e a alquimia, onde em suas cartas há uma correspondência alquímica, um signo astrológico e um número para cada arquétipo. As cartas podem ser consideradas uma jornada que nos ajuda a obter uma melhor compreensão do passado, presente e futuro.': 'Tarot is a mirror of our soul and reflects the full spectrum of human experience through archetypes. It is an ancient connection between humanity and the divine, guiding us toward something greater. Studying Tarot is a journey of inner discovery that helps us understand ourselves and the present moment. It walks alongside astrology and alchemy, with an alchemical correspondence, an astrological sign, and a number for each archetype. The cards can be seen as a journey toward a deeper understanding of the past, present, and future.'
  },
  es: {
    'Saiba que o Tarot é um espelho da nossa alma e reflete todo o espectro da experiência humana através de arquétipos. É uma das conexões mais antigas entre os seres humanos e as divindades, tendo o papel de nos aproximar de algo superior. Seu estudo representa uma viagem de descoberta interior, onde passamos a conhecer melhor a nós mesmos e o atual momento o qual estamos inseridos. É um oráculo que caminha lado a lado com a astrologia e a alquimia, onde em suas cartas há uma correspondência alquímica, um signo astrológico e um número para cada arquétipo. As cartas podem ser consideradas uma jornada que nos ajuda a obter uma melhor compreensão do passado, presente e futuro.': 'El Tarot es un espejo de nuestra alma y refleja todo el espectro de la experiencia humana a través de arquetipos. Es una de las conexiones más antiguas entre los seres humanos y lo divino, y nos acerca a algo superior. Su estudio es un viaje de descubrimiento interior que nos ayuda a conocernos mejor y comprender el momento presente. Camina junto a la astrología y la alquimia, con una correspondencia alquímica, un signo astrológico y un número para cada arquetipo. Las cartas pueden considerarse un viaje que nos ayuda a comprender mejor el pasado, presente y futuro.'
  },
  de: {
    'Saiba que o Tarot é um espelho da nossa alma e reflete todo o espectro da experiência humana através de arquétipos. É uma das conexões mais antigas entre os seres humanos e as divindades, tendo o papel de nos aproximar de algo superior. Seu estudo representa uma viagem de descoberta interior, onde passamos a conhecer melhor a nós mesmos e o atual momento o qual estamos inseridos. É um oráculo que caminha lado a lado com a astrologia e a alquimia, onde em suas cartas há uma correspondência alquímica, um signo astrológico e um número para cada arquétipo. As cartas podem ser consideradas uma jornada que nos ajuda a obter uma melhor compreensão do passado, presente e futuro.': 'Das Tarot ist ein Spiegel unserer Seele und reflektiert das gesamte Spektrum menschlicher Erfahrung durch Archetypen. Es gehört zu den ältesten Verbindungen zwischen Mensch und Göttlichem und kann uns etwas Höherem näherbringen. Sein Studium ist eine Reise der inneren Entdeckung, die uns hilft, uns selbst und den gegenwärtigen Moment besser zu verstehen. Es geht Hand in Hand mit Astrologie und Alchemie, mit einer alchemistischen Entsprechung, einem astrologischen Zeichen und einer Zahl für jeden Archetyp. Die Karten können als Reise zu einem besseren Verständnis von Vergangenheit, Gegenwart und Zukunft betrachtet werden.'
  },
  fr: {
    'Saiba que o Tarot é um espelho da nossa alma e reflete todo o espectro da experiência humana através de arquétipos. É uma das conexões mais antigas entre os seres humanos e as divindades, tendo o papel de nos aproximar de algo superior. Seu estudo representa uma viagem de descoberta interior, onde passamos a conhecer melhor a nós mesmos e o atual momento o qual estamos inseridos. É um oráculo que caminha lado a lado com a astrologia e a alquimia, onde em suas cartas há uma correspondência alquímica, um signo astrológico e um número para cada arquétipo. As cartas podem ser consideradas uma jornada que nos ajuda a obter uma melhor compreensão do passado, presente e futuro.': 'Sachez que le Tarot est un miroir de notre âme et reflète tout le spectre de l’expérience humaine à travers les archétypes. Il constitue l’une des plus anciennes connexions entre les êtres humains et le divin, nous rapprochant de quelque chose de supérieur. Son étude est un voyage de découverte intérieure qui nous aide à mieux nous connaître et à comprendre le moment présent. Il accompagne l’astrologie et l’alchimie, avec une correspondance alchimique, un signe astrologique et un nombre pour chaque archétype. Les cartes peuvent être considérées comme un voyage vers une meilleure compréhension du passé, du présent et du futur.'
  }
};
