import { Language } from './types';

export const tarotTranslations: Record<Language, Record<string, string>> = {
  pt: {
    tarotWelcome: 'Seja bem-vindo ao Oráculo do Tarot',
    tarotDescription: 'O Tarot é um espelho da nossa alma e reflete todo o espectro da experiência humana através de arquétipos. Use-o para obter uma melhor compreensão do passado, presente e futuro.',
    drawCards: 'Tirar Cartas (Passado, Presente, Futuro)',
    tarotStudy: 'O Tarot caminha lado a lado com a astrologia e a alquimia, onde em suas cartas há uma correspondência alquímica, um signo astrológico e um número para cada arquétipo.',
    readingPast: 'Passado', readingPresent: 'Presente', readingFuture: 'Futuro',
    'Saiba que o Tarot é um espelho da nossa alma e reflete todo o espectro da experiência humana através de arquétipos. É uma das conexões mais antigas entre os seres humanos e as divindades, tendo o papel de nos aproximar de algo superior. Seu estudo representa uma viagem de descoberta interior, onde passamos a conhecer melhor a nós mesmos e o atual momento o qual estamos inseridos. É um oráculo que caminha lado a lado com a astrologia e a alquimia, onde em suas cartas há uma correspondência alquímica, um signo astrológico e um número para cada arquétipo. As cartas podem ser consideradas uma viagem que nos ajuda a obter uma melhor compreensão do passado, presente e futuro.': 'Saiba que o Tarot é um espelho da nossa alma e reflete todo o espectro da experiência humana através de arquétipos. É uma das conexões mais antigas entre os seres humanos e as divindades, tendo o papel de nos aproximar de algo superior. Seu estudo representa uma viagem de descoberta interior, onde passamos a conhecer melhor a nós mesmos e o atual momento o qual estamos inseridos. É um oráculo que caminha lado a lado com a astrologia e a alquimia, onde em suas cartas há uma correspondência alquímica, um signo astrológico e um número para cada arquétipo. As cartas podem ser consideradas uma viagem que nos ajuda a obter uma melhor compreensão do passado, presente e futuro.',
    'Embaralhando as lâminas sagradas...': 'Embaralhando as lâminas sagradas...', 'Mentalize sua pergunta antes de virar as cartas': 'Mentalize sua pergunta antes de virar as cartas', 'Sua consulta de tarot foi interpretada por IA!': 'Sua consulta de tarot foi interpretada por IA!', 'Consultar Oráculo de Tarot': 'Consultar Oráculo de Tarot', 'Vire as três cartas para revelar a leitura': 'Vire as três cartas para revelar a leitura', Carta: 'Carta', Cartas: 'Cartas', Arcano: 'Arcano', Significado: 'Significado', Posição: 'Posição', 'Conselho Cósmico': 'Conselho Cósmico'
  },
  en: {
    tarotWelcome: 'Welcome to the Tarot Oracle', tarotDescription: 'Tarot is a mirror of our soul and reflects the entire spectrum of human experience through archetypes. Use it to gain a better understanding of the past, present, and future.', drawCards: 'Draw Cards (Past, Present, Future)', tarotStudy: 'Tarot walks hand in hand with astrology and alchemy, where in its cards there is an alchemical correspondence, an astrological sign, and a number for each archetype.', readingPast: 'Past', readingPresent: 'Present', readingFuture: 'Future',
    'Saiba que o Tarot é um espelho da nossa alma e reflete todo o espectro da experiência humana através de arquétipos. É uma das conexões mais antigas entre os seres humanos e as divindades, tendo o papel de nos aproximar de algo superior. Seu estudo representa uma viagem de descoberta interior, onde passamos a conhecer melhor a nós mesmos e o atual momento o qual estamos inseridos. É um oráculo que caminha lado a lado com a astrologia e a alquimia, onde em suas cartas há uma correspondência alquímica, um signo astrológico e um número para cada arquétipo. As cartas podem ser consideradas uma viagem que nos ajuda a obter uma melhor compreensão do passado, presente e futuro.': 'Know that Tarot is a mirror of our soul and reflects the entire spectrum of human experience through archetypes. It is one of the oldest connections between humanity and the divine, bringing us closer to something greater. Its study is a journey of inner discovery that helps us understand ourselves and the present moment. It walks alongside astrology and alchemy, with an alchemical correspondence, an astrological sign, and a number for each archetype. The cards can be viewed as a journey toward a deeper understanding of the past, present, and future.',
    'Embaralhando as lâminas sagradas...': 'Shuffling the sacred cards...', 'Mentalize sua pergunta antes de virar as cartas': 'Focus on your question before flipping the cards', 'Sua consulta de tarot foi interpretada por IA!': 'Your tarot reading has been interpreted by AI!', 'Consultar Oráculo de Tarot': 'Consult Tarot Oracle', 'Vire as três cartas para revelar a leitura': 'Flip the three cards to reveal your reading', Carta: 'Card', Cartas: 'Cards', Arcano: 'Arcanum', Significado: 'Meaning', Posição: 'Position', 'Conselho Cósmico': 'Cosmic Advice'
  },
  es: {
    tarotWelcome: 'Bienvenido al Oráculo del Tarot', tarotDescription: 'El Tarot es un espejo de nuestra alma y refleja todo el espectro de la experiencia humana a través de arquetipos. Úselo para obtener una mejor comprensión del pasado, presente y futuro.', drawCards: 'Tirar Cartas (Pasado, Presente, Futuro)', tarotStudy: 'El Tarot camina de la mano con la astrología y la alquimia, donde en sus cartas hay una correspondencia alquímica, un signo astrológico y un número para cada arquetipo.', readingPast: 'Pasado', readingPresent: 'Presente', readingFuture: 'Futuro',
    'Saiba que o Tarot é um espelho da nossa alma e reflete todo o espectro da experiência humana através de arquétipos. É uma das conexões mais antigas entre os seres humanos e as divindades, tendo o papel de nos aproximar de algo superior. Seu estudo representa uma viagem de descoberta interior, onde passamos a conhecer melhor a nós mesmos e o atual momento o qual estamos inseridos. É um oráculo que caminha lado a lado com a astrologia e a alquimia, onde em suas cartas há uma correspondência alquímica, um signo astrológico e um número para cada arquétipo. As cartas podem ser consideradas uma viagem que nos ajuda a obter uma melhor compreensão do passado, presente e futuro.': 'El Tarot es un espejo de nuestra alma y refleja todo el espectro de la experiencia humana a través de arquetipos. Es una de las conexiones más antiguas entre la humanidad y lo divino, y nos acerca a algo superior. Su estudio es un viaje de descubrimiento interior que nos ayuda a comprendernos mejor y entender el momento presente. Camina junto a la astrología y la alquimia, con una correspondencia alquímica, un signo astrológico y un número para cada arquetipo. Las cartas pueden considerarse un viaje hacia una mejor comprensión del pasado, presente y futuro.',
    'Embaralhando as lâminas sagradas...': 'Barajando las cartas sagradas...', 'Mentalize sua pergunta antes de virar as cartas': 'Mentalice su pregunta antes de voltear las cartas', 'Sua consulta de tarot foi interpretada por IA!': '¡Su consulta de tarot ha sido interpretada por IA!', 'Consultar Oráculo de Tarot': 'Consultar el Oráculo del Tarot', 'Vire as três cartas para revelar a leitura': 'Voltee las tres cartas para revelar la lectura', Carta: 'Carta', Cartas: 'Cartas', Arcano: 'Arcano', Significado: 'Significado', Posição: 'Posición', 'Conselho Cósmico': 'Consejo Cósmico'
  },
  de: {
    tarotWelcome: 'Willkommen beim Tarot-Orakel', tarotDescription: 'Das Tarot ist ein Spiegel unserer Seele und reflektiert das gesamte Spektrum der menschlichen Erfahrung durch Archetypen. Nutzen Sie es für ein besseres Verständnis von Vergangenheit, Gegenwart und Zukunft.', drawCards: 'Karten ziehen (Vergangenheit, Gegenwart, Zukunft)', tarotStudy: 'Das Tarot geht Hand in Hand mit Astrologie und Alchemie, wobei auf seinen Karten für jeden Archetyp eine alchemistische Entsprechung, ein astrologisches Zeichen und eine Zahl angegeben sind.', readingPast: 'Vergangenheit', readingPresent: 'Gegenwart', readingFuture: 'Zukunft',
    'Saiba que o Tarot é um espelho da nossa alma e reflete todo o espectro da experiência humana através de arquétipos. É uma das conexões mais antigas entre os seres humanos e as divindades, tendo o papel de nos aproximar de algo superior. Seu estudo representa uma viagem de descoberta interior, onde passamos a conhecer melhor a nós mesmos e o atual momento o qual estamos inseridos. É um oráculo que caminha lado a lado com a astrologia e a alquimia, onde em suas cartas há uma correspondência alquímica, um signo astrológico e um número para cada arquétipo. As cartas podem ser consideradas uma viagem que nos ajuda a obter uma melhor compreensão do passado, presente e futuro.': 'Das Tarot ist ein Spiegel unserer Seele und reflektiert das gesamte Spektrum menschlicher Erfahrung durch Archetypen. Es gehört zu den ältesten Verbindungen zwischen Menschen und dem Göttlichen und kann uns etwas Höherem näherbringen. Sein Studium ist eine Reise der inneren Entdeckung, die uns hilft, uns selbst und den gegenwärtigen Moment besser zu verstehen. Es geht Hand in Hand mit Astrologie und Alchemie, mit einer alchemistischen Entsprechung, einem astrologischen Zeichen und einer Zahl für jeden Archetyp. Die Karten können als Reise zu einem besseren Verständnis von Vergangenheit, Gegenwart und Zukunft betrachtet werden.',
    'Embaralhando as lâminas sagradas...': 'Die heiligen Karten werden gemischt...', 'Mentalize sua pergunta antes de virar as cartas': 'Konzentrieren Sie sich auf Ihre Frage, bevor Sie die Karten umdrehen', 'Sua consulta de tarot foi interpretada por IA!': 'Ihre Tarot-Lesung wurde von der KI interpretiert!', 'Consultar Oráculo de Tarot': 'Tarot-Orakel konsultieren', 'Vire as três cartas para revelar a leitura': 'Drehen Sie die drei Karten um, um die Lesung zu enthüllen', Carta: 'Karte', Cartas: 'Karten', Arcano: 'Arkanum', Significado: 'Bedeutung', Posição: 'Position', 'Conselho Cósmico': 'Kosmischer Rat'
  },
  fr: {
    tarotWelcome: "Bienvenue dans l'Oracle de Tarot", tarotDescription: "Le Tarot est un miroir de notre âme et reflète tout le spectre de l'expérience humaine à travers des archétypes. Utilisez-le pour mieux comprendre le passé, le présent et le futur.", drawCards: 'Tirer des Cartes (Passé, Présent, Futur)', tarotStudy: "Le Tarot marche main dans la main avec l'astrologie et l'alchimie, avec une correspondance alchimique, un signe astrologique et un nombre pour chaque archétype.", readingPast: 'Passé', readingPresent: 'Présent', readingFuture: 'Futur',
    'Saiba que o Tarot é um espelho da nossa alma e reflete todo o espectro da experiência humana através de arquétipos. É uma das conexões mais antigas entre os seres humanos e as divindades, tendo o papel de nos aproximar de algo superior. Seu estudo representa uma viagem de descoberta interior, onde passamos a conhecer melhor a nós mesmos e o atual momento o qual estamos inseridos. É um oráculo que caminha lado a lado com a astrologia e a alquimia, onde em suas cartas há uma correspondência alquímica, um signo astrológico e um número para cada arquétipo. As cartas podem ser consideradas uma viagem que nos ajuda a obter uma melhor compreensão do passado, presente e futuro.': "Sachez que le Tarot est un miroir de notre âme et reflète tout le spectre de l'expérience humaine à travers les archétypes. Il constitue l'une des plus anciennes connexions entre l'humanité et le divin et nous rapproche de quelque chose de supérieur. Son étude est un voyage de découverte intérieure qui nous aide à mieux nous connaître et à comprendre le moment présent. Il accompagne l'astrologie et l'alchimie, avec une correspondance alchimique, un signe astrologique et un nombre pour chaque archétype. Les cartes peuvent être considérées comme un voyage vers une meilleure compréhension du passé, du présent et du futur.",
    'Embaralhando as lâminas sagradas...': 'Mélange des cartes sacrées...', 'Mentalize sua pergunta antes de virar as cartas': 'Pensez à votre question avant de retourner les cartes', 'Sua consulta de tarot foi interpretada por IA!': 'Votre tirage de tarot a été interprété par l’IA !', 'Consultar Oráculo de Tarot': "Consulter l'Oracle de Tarot", 'Vire as três cartas para revelar a leitura': 'Retournez les trois cartes pour révéler le tirage', Carta: 'Carte', Cartas: 'Cartes', Arcano: 'Arcane', Significado: 'Signification', Posição: 'Position', 'Conselho Cósmico': 'Conseil cosmique'
  }
};